### ISSUE TITLE
Include boot logs with mayday

### ISSUE THREAD

**Issue by grepory** [flatcar-linux/mayday#2]
**Current situation**
Mayday does not include boot logs.

**Impact**
We have to SSH to machines to view boot logs on machines that panic.

**Ideal future situation**
Automatically include boot logs.

**Implementation options**
Run `journalctl -b -1` and record the output.

**Comment by pothos** [comment]
A PR for that is in https://github.com/flatcar-linux/mayday/pull/6 (both for the current boot and the previous boot).

**Comment by pothos** [comment]
Merged and scheduled for inclusion in the next Alpha and Edge release, then the following Beta and Stable releases.
