### ISSUE TITLE
Add the contents of /sys/fs/pstore to mayday tarballs

### ISSUE THREAD

**Issue by grepory** [flatcar-linux/mayday#3]
**Current situation**
See https://github.com/flatcar-linux/mayday/issues/1 for context.

All documentation about acquiring core dumps from Flatcar / CoreOS refer to /sys/fs/pstore and ERST logs. You can't get these logs in mayday, and when diagnosing a kernel panic they are required.

**Impact**
Diagnosing kernel panics is very challenging on large fleets.

**Ideal future situation**
These files are included automatically if they exist.

**Comment by pothos** [comment]
If in the future people have `systemd-pstore.service` enabled to automatically clean pstore, we should also cover `/var/lib/systemd/pstore/` where the dumps are moved from pstore.

**Comment by pothos** [comment]
PR is here: https://github.com/flatcar-linux/mayday/pull/7

**Comment by pothos** [comment]
Merged and scheduled for inclusion in the next Alpha and Edge release, then the following Beta and Stable releases.
